services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/audioupe"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=audioupe'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
